In [56]:
import numpy as np
from scipy.linalg import solveh_banded
from scipy.linalg import eig

In [10]:
#### a. Define a matrix A
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#### b. Define a vector b
b = np.array([1,2,3])
b

array([1, 2, 3])

In [22]:
#### c. Solve the linear system of equations A x = b
a = solveh_banded(m,b)
a

array([ 9.28829786e-17, -1.99271519e-16,  3.33333333e-01])

In [51]:
#### d. Check that your solution is correct by plugging it into the equation
print(a[0]*m[0][0] + a[1]*m[0][1] + a[2]*m[0][2])
print(a[0]*m[1][0] + a[1]*m[1][1] + a[2]*m[1][2])
print(a[0]*m[2][0] + a[1]*m[2][1] + a[2]*m[2][2])

1.0000000000000002
2.0000000000000004
3.0000000000000004


In [54]:
#### e. Repeat steps a-d using a random 3x3 matrix B (instead of the vector b)

br = np.random.random((3, 3))
ar = solveh_banded(m,br)
ar

array([[ 0.19136329,  0.24050923,  0.21939752],
       [-0.18298155, -0.22857713, -0.1475108 ],
       [ 0.12271056,  0.14109559,  0.04883852]])

In [58]:
#### f. Solve the eigenvalue problem for the matrix A and print the eigenvalues and eigenvectors

e = eig(m)
e

(array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -9.75918483e-16+0.j]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))